### ISSUE TITLE
A basic list of features for the forum

### ISSUE THREAD

**Issue by ayys** [SiyaOrg/e-sawal#3]
## Task list of Ideas

1. A simple Question and Answer System with support for images and [LaTex](http://www.latex-project.org/) (maybe using [pandoc](http://pandoc.org/)?)
2. A purely front end chat system for discussions (maybe something like [hack.chat](https://hack.chat/)?)
3. A rating system for answers

## Some thoughts about the rating system

The rating system can be simple. Each user can up-vote an answer. The most voted answer will be the most relevant.
The no. of votes for a question will be the ratio of :
- Sum of votes given to all the answers
- The number of answers to the question

So a question with the most votes and the most number of answers  will be the most relevant.
<hr>
A lot of us have exams going on right now, so we haven't been able to focus on @SiyaOrg lately.
The exams will finish on 26<sup>th</sup> January, so sit tight! :smile: 

_P.S. - Hope this helps move e-sawal forward! I will write a simple project home page for e-sawal after my exams finish (unless someone else doesn't do it :rofl: )_

**Comment by anurag1234565** [comment]
I will do chat system .... :smile: :laughing:

**Comment by ayys** [comment]
hack.chat bata banaaune? @anurag1234565 euta prototype banayera add gara na..add garda naya branch ma garnu, master ma haina

**Comment by krrishg** [comment]
add me

**Comment by ayys** [comment]
@krrishg I addded u :smile:

**Comment by bravegurkha** [comment]
Maile yo project ma chai k garam ? @ayys

**Comment by ayys** [comment]
@bravegurkha simple [angular](https://angularjs.org/) interface banau na.
Aile ko lagi, yo points haru banaau na
- [ ] A way to post questions
- [ ] A way to reply to the questions
- [ ] A home page with all the questions

Ani aafno code lai naya branch ma rakhnu hai. 
#### [naya branch banaune tarika](https://github.com/blog/1377-create-and-delete-branches)

**Comment by anurag1234565** [comment]
@ayys ma mero kaam chai exam paxi suru garxu hai .. ( is that ok?)

**Comment by ayys** [comment]
huncha. Ma pani exams pachi nai start garchu :stuck_out_tongue_winking_eye:

**Comment by akhil123pp** [comment]
ma kaile bata start garau ??? :P

**Comment by ayys** [comment]
# ई-सवालको गृहपृष्टको चित्र

![drawing](https://cloud.githubusercontent.com/assets/7620571/21775984/712e7a66-d6c0-11e6-8893-1de40222a4ca.png)

@akhil123pp तिमी यो पृष्टको रूपरेखा बनाउ न _!_ :+1:
